version: "3.9"

services:
  app:
    container_name: infusion-drop
    image: webapp-infusion-drop
    ports:
      - "8901:8901"
    stdin_open: true
    tty: true
    volumes:
      - webapp-infusion-drop-models-vol:/app

volumes:
  webapp-infusion-drop-vol:
    name: webapp-infusion-drop-vol
